puts "This string has a quote: \".  As you can see, it is escaped"
puts "This quote by me: \"lol\""
puts "There is a tab here: \t waaaat"
puts "Disabling interpolation: \#{1+1}"
p :"my_symbol"
p :"my_symbol#{1+1}"
